version: 2.1

commands:
  print_pipeline_id:
    description: "Print Pipeline ID"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}


jobs:
  my_job:

    docker: 
      - image: cimg/base:stable

    steps:
      -  print_pipeline_id

  
workflows:
  printing_pipeline_id:
    jobs:
      - my_job